/**
 * @file glyph.h
 *
 * @author Michael Ciuffo <ch0000f@gmail.com> 24 Jan 2014
 *
 * Font for Wavetag DVT1
 */

#ifndef GLYPH_H_
#define GLYPH_H_

#include <stdint.h>
#include <avr/pgmspace.h>


/**
 * Raw pixel data for A-Z, 0-9, and some symbols
 */
extern const uint8_t GLYPH_DATA[] PROGMEM;


/**
 * Width of each individual symbol
 */
extern const uint8_t GLYPH_WIDTH[] PROGMEM;


/**
 * Location of the beginning of each symbol. Can be generated by a
 * running sum of
 */
extern const uint8_t GLYPH_IDX[] PROGMEM;

#endif // GLYPH_H_
